//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsyncController.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InfiniteDBEntities : DbContext
    {
        public InfiniteDBEntities()
            : base("name=InfiniteDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<dept> depts { get; set; }
        public virtual DbSet<emp> emps { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<empnormal> empnormals { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductSale> ProductSales { get; set; }
        public virtual DbSet<dummy> dummies { get; set; }
        public virtual DbSet<empdata> empdatas { get; set; }
        public virtual DbSet<Utable1> Utable1 { get; set; }
        public virtual DbSet<Utable2> Utable2 { get; set; }
    }
}
