<?xml version="1.0" encoding="utf-8"?><Database Name="InfiniteDB" Class="LS_VSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-TJJ7D977;Initial Catalog=InfiniteDB;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="LinqToSQL_VS.Properties.Settings" SettingsPropertyName="InfiniteDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.emp" Member="emps">
    <Type Name="emp">
      <Column Name="empno" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ename" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="job" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="mgr_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hire_date" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="salary" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="comm" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="deptno" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="EmpId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EmpName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="Char(7)" CanBeNull="true" />
      <Column Name="Salary" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="DepartmentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="AnnualSalary" Type="System.Decimal" DbType="Decimal(21,0)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Function Name="dbo.GetSal_byName" Method="GetSal_byName">
    <Parameter Name="ename" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="salary" Type="System.Double" DbType="Float" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>